FROM node:slim as builder


# Create app direcotiy

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

# Installing dependencies
COPY package.json .

COPY yarn.lock .

RUN yarn

# Copy source files
COPY . .

# Building app
RUN yarn build


FROM nginx:alpine

RUN mkdir /usr/share/nginx/buffer

COPY --from=builder /usr/src/app/.next /usr/share/nginx/buffer

COPY --from=builder /usr/src/app/deploy.sh /usr/share/nginx/buffer

RUN chmod +x /usr/share/nginx/buffer/deploy.sh

RUN cd /usr/share/nginx/buffer && ./deploy.sh

RUN mkdir /usr/share/nginx/log

RUN rm /etc/nginx/conf.d/default.conf

COPY ./nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]